import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Use simple Poppins (regular weight)
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased m-0 p-0 min-h-screen relative`}
      >
        {/* Header */}
        <header className="fixed top-0 right-0 h-screen flex flex-col justify-start items-end z-20 p-8 gap-8 pointer-events-none">
          <nav className="flex flex-col gap-4 pointer-events-auto">
            <a
              href="#about"
              className="text-white text-xl no-underline font-light font-sans"
              style={{ fontFamily: "var(--font-poppins), sans-serif" }}
            >
              About
            </a>
            <a
              href="#work"
              className="text-white text-xl no-underline font-light font-sans"
              style={{ fontFamily: "var(--font-poppins), sans-serif" }}
            >
              Work
            </a>
            <a
              href="#contact"
              className="text-white text-xl no-underline font-light font-sans"
              style={{ fontFamily: "var(--font-poppins), sans-serif" }}
            >
              Contact
            </a>
          </nav>
        </header>
        {/* Main Content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
